tunnel: 556edbaf-17a9-4841-a284-6134f09230e0
credentials-file: /root/copilotprotheus/config/556edbaf-17a9-4841-a284-6134f09230e0.json

ingress:
  - hostname: copilot.elitecorp.tec.br
    service: http://localhost:3001
  - service: http_status:404
