tunnel: 7eafecde-b82a-4d65-9db7-42fe116f43ec
credentials-file: /root/copilotprotheus/config/7eafecde-b82a-4d65-9db7-42fe116f43ec.json

ingress:
  - hostname: copilot.elitecorp.tec.br
    service: http://localhost:3001
  - hostname: copílot-admin.elitecorp.tec.br
    service: http://localhost:5174
  - service: http_status:404
