"""Initial schema

Revision ID: 65ec11a486ca
Revises: 
Create Date: 2026-06-27 14:32:34.322872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ec11a486ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('environment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('station', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assistant_audit_pkey'))
    )
    # ### end Alembic commands ###
